### ISSUE TITLE
excited with code 1

### ISSUE THREAD

**Issue by QuantumRage100** [DRSchlaubi/mikbot#218]
I'm having a bit of trouble getting this bot to run, I have docker and lavalink installed, I have created changed my .env and created the docker-compose.yml as well when I try to run the bot it just ends up exciting with code 1
would you be able to point and laughing at me before telling me what I'm doing wrong?

Microsoft Windows [Version 10.0.19044.1889]
(c) Microsoft Corporation. All rights reserved.

C:\WINDOWS\system32>cd C:\Music-Bot-2

C:\Music-Bot-2>docker-compose up -d
[+] Running 16/16
 - bot Pulled                                                                                                     23.4s
   - 675920708c8b Pull complete                                                                                    7.7s
   - 8d642f39b108 Pull complete                                                                                    8.3s
   - 9f4772666698 Pull complete                                                                                   15.4s
   - b3ad047f9def Pull complete                                                                                   15.6s
   - 4844e895491a Pull complete                                                                                   15.7s
   - bc78e3c069ed Pull complete                                                                                   21.9s
 - mongo Pulled                                                                                                   42.1s
   - 6f9c8c301e0f Pull complete                                                                                    5.0s
   - 73738965c4ce Pull complete                                                                                    6.7s
   - 7fd6635b9ddf Pull complete                                                                                    8.7s
   - 73a471eaa4ad Pull complete                                                                                    9.6s
   - bcf274af89b0 Pull complete                                                                                   10.7s
   - 04fc489f2a3b Pull complete                                                                                   11.6s
   - 6eff8a505292 Pull complete                                                                                   36.6s
   - a5ef4431fce7 Pull complete                                                                                   36.7s
[+] Running 4/4
 - Network music-bot-2_default      Created                                                                        0.6s
 - Volume "music-bot-2_mongo-data"  Created                                                                        0.0s
 - Container music-bot-2-mongo-1    Started                                                                        7.6s
 - Container music-bot-2-bot-1      Started                                                                        2.0s

[+] Running 2/2docker-compose up
 - Container music-bot-2-mongo-1  Recreated                                                                        0.6s
 - Container music-bot-2-bot-1    Recreated                                                                        0.2s
Attaching to music-bot-2-bot-1, music-bot-2-mongo-1
music-bot-2-mongo-1  | {"t":{"$date":"2022-09-10T00:30:11.389+00:00"},"s":"I",  "c":"NETWORK",  "id":4915701, "ctx":"-","msg":"Initialized wire specification","attr":{"spec":{"incomingExternalClient":{"minWireVersion":0,"maxWireVersion":17},"incomingInternalClient":{"minWireVersion":0,"maxWireVersion":17},"outgoing":{"minWireVersion":6,"maxWireVersion":17},"isInternalClient":true}}}
music-bot-2-mongo-1  | {"t":{"$date":"2022-09-10T00:30:11.389+00:00"},"s":"I",  "c":"CONTROL",  "id":23285,   "ctx":"main","msg":"Automatically disabling TLS 1.0, to force-enable TLS 1.0 specify --sslDisabledProtocols 'none'"}
music-bot-2-mongo-1  | {"t":{"$date":"2022-09-10T00:30:11.390+00:00"},"s":"I",  "c":"NETWORK",  "id":4648601, "ctx":"main","msg":"Implicit TCP FastOpen unavailable. If TCP FastOpen is required, set tcpFastOpenServer, tcpFastOpenClient, and tcpFastOpenQueueSize."}
music-bot-2-mongo-1  | {"t":{"$date":"2022-09-10T00:30:11.390+00:00"},"s":"I",  "c":"REPL",     "id":5123008, "ctx":"main","msg":"Successfully registered PrimaryOnlyService","attr":{"service":"TenantMigrationDonorService","namespace":"config.tenantMigrationDonors"}}
music-bot-2-mongo-1  | {"t":{"$date":"2022-09-10T00:30:11.390+00:00"},"s":"I",  "c":"REPL",     "id":5123008, "ctx":"main","msg":"Successfully registered PrimaryOnlyService","attr":{"service":"TenantMigrationRecipientService","namespace":"config.tenantMigrationRecipients"}}
music-bot-2-mongo-1  | {"t":{"$date":"2022-09-10T00:30:11.390+00:00"},"s":"I",  "c":"REPL",     "id":5123008, "ctx":"main","msg":"Successfully registered PrimaryOnlyService","attr":{"service":"ShardSplitDonorService","namespace":"config.tenantSplitDonors"}}
music-bot-2-mongo-1  | {"t":{"$date":"2022-09-10T00:30:11.390+00:00"},"s":"I",  "c":"CONTROL",  "id":5945603, "ctx":"main","msg":"Multi threading initialized"}
music-bot-2-mongo-1  | {"t":{"$date":"2022-09-10T00:30:11.391+00:00"},"s":"I",  "c":"CONTROL",  "id":4615611, "ctx":"initandlisten","msg":"MongoDB starting","attr":{"pid":1,"port":27017,"dbPath":"/data/db","architecture":"64-bit","host":"5a9af1a27d43"}}
music-bot-2-mongo-1  | {"t":{"$date":"2022-09-10T00:30:11.391+00:00"},"s":"I",  "c":"CONTROL",  "id":23403,   "ctx":"initandlisten","msg":"Build Info","attr":{"buildInfo":{"version":"6.0.1","gitVersion":"32f0f9c88dc44a2c8073a5bd47cf779d4bfdee6b","openSSLVersion":"OpenSSL 1.1.1f  31 Mar 2020","modules":[],"allocator":"tcmalloc","environment":{"distmod":"ubuntu2004","distarch":"x86_64","target_arch":"x86_64"}}}}
music-bot-2-mongo-1  | {"t":{"$date":"2022-09-10T00:30:11.391+00:00"},"s":"I",  "c":"CONTROL",  "id":51765,   "ctx":"initandlisten","msg":"Operating System","attr":{"os":{"name":"Ubuntu","version":"20.04"}}}
music-bot-2-mongo-1  | {"t":{"$date":"2022-09-10T00:30:11.391+00:00"},"s":"I",  "c":"CONTROL",  "id":21951,   "ctx":"initandlisten","msg":"Options set by command line","attr":{"options":{"net":{"bindIp":"*"},"security":{"authorization":"enabled"}}}}
music-bot-2-mongo-1  | {"t":{"$date":"2022-09-10T00:30:11.391+00:00"},"s":"I",  "c":"STORAGE",  "id":22270,   "ctx":"initandlisten","msg":"Storage engine to use detected by data files","attr":{"dbpath":"/data/db","storageEngine":"wiredTiger"}}
music-bot-2-mongo-1  | {"t":{"$date":"2022-09-10T00:30:11.391+00:00"},"s":"I",  "c":"STORAGE",  "id":22297,   "ctx":"initandlisten","msg":"Using the XFS filesystem is strongly recommended with the WiredTiger storage engine. See http://dochub.mongodb.org/core/prodnotes-filesystem","tags":["startupWarnings"]}
music-bot-2-mongo-1  | {"t":{"$date":"2022-09-10T00:30:11.391+00:00"},"s":"I",  "c":"STORAGE",  "id":22315,   "ctx":"initandlisten","msg":"Opening WiredTiger","attr":{"config":"create,cache_size=25163M,session_max=33000,eviction=(threads_min=4,threads_max=4),config_base=false,statistics=(fast),log=(enabled=true,remove=true,path=journal,compressor=snappy),builtin_extension_config=(zstd=(compression_level=6)),file_manager=(close_idle_time=600,close_scan_interval=10,close_handle_minimum=2000),statistics_log=(wait=0),json_output=(error,message),verbose=[recovery_progress:1,checkpoint_progress:1,compact_progress:1,backup:0,checkpoint:0,compact:0,evict:0,history_store:0,recovery:0,rts:0,salvage:0,tiered:0,timestamp:0,transaction:0,verify:0,log:0],"}}
music-bot-2-mongo-1  | {"t":{"$date":"2022-09-10T00:30:11.655+00:00"},"s":"I",  "c":"STORAGE",  "id":4795906, "ctx":"initandlisten","msg":"WiredTiger opened","attr":{"durationMillis":264}}
music-bot-2-mongo-1  | {"t":{"$date":"2022-09-10T00:30:11.655+00:00"},"s":"I",  "c":"RECOVERY", "id":23987,   "ctx":"initandlisten","msg":"WiredTiger recoveryTimestamp","attr":{"recoveryTimestamp":{"$timestamp":{"t":0,"i":0}}}}
music-bot-2-mongo-1  | {"t":{"$date":"2022-09-10T00:30:11.655+00:00"},"s":"I",  "c":"WT",       "id":4366408, "ctx":"initandlisten","msg":"No table logging settings modifications are required for existing WiredTiger tables","attr":{"loggingEnabled":true}}
music-bot-2-mongo-1  | {"t":{"$date":"2022-09-10T00:30:11.674+00:00"},"s":"W",  "c":"CONTROL",  "id":22178,   "ctx":"initandlisten","msg":"/sys/kernel/mm/transparent_hugepage/enabled is 'always'. We suggest setting it to 'never'","tags":["startupWarnings"]}
music-bot-2-mongo-1  | {"t":{"$date":"2022-09-10T00:30:11.674+00:00"},"s":"W",  "c":"CONTROL",  "id":5123300, "ctx":"initandlisten","msg":"vm.max_map_count is too low","attr":{"currentValue":65530,"recommendedMinimum":1677720,"maxConns":838860},"tags":["startupWarnings"]}
music-bot-2-mongo-1  | {"t":{"$date":"2022-09-10T00:30:11.675+00:00"},"s":"I",  "c":"NETWORK",  "id":4915702, "ctx":"initandlisten","msg":"Updated wire specification","attr":{"oldSpec":{"incomingExternalClient":{"minWireVersion":0,"maxWireVersion":17},"incomingInternalClient":{"minWireVersion":0,"maxWireVersion":17},"outgoing":{"minWireVersion":6,"maxWireVersion":17},"isInternalClient":true},"newSpec":{"incomingExternalClient":{"minWireVersion":0,"maxWireVersion":17},"incomingInternalClient":{"minWireVersion":17,"maxWireVersion":17},"outgoing":{"minWireVersion":17,"maxWireVersion":17},"isInternalClient":true}}}
music-bot-2-mongo-1  | {"t":{"$date":"2022-09-10T00:30:11.675+00:00"},"s":"I",  "c":"REPL",     "id":5853300, "ctx":"initandlisten","msg":"current featureCompatibilityVersion value","attr":{"featureCompatibilityVersion":"6.0","context":"startup"}}
music-bot-2-mongo-1  | {"t":{"$date":"2022-09-10T00:30:11.675+00:00"},"s":"I",  "c":"STORAGE",  "id":5071100, "ctx":"initandlisten","msg":"Clearing temp directory"}
music-bot-2-mongo-1  | {"t":{"$date":"2022-09-10T00:30:11.675+00:00"},"s":"I",  "c":"CONTROL",  "id":20536,   "ctx":"initandlisten","msg":"Flow Control is enabled on this deployment"}
music-bot-2-mongo-1  | {"t":{"$date":"2022-09-10T00:30:11.675+00:00"},"s":"I",  "c":"FTDC",     "id":20625,   "ctx":"initandlisten","msg":"Initializing full-time diagnostic data capture","attr":{"dataDirectory":"/data/db/diagnostic.data"}}
music-bot-2-mongo-1  | {"t":{"$date":"2022-09-10T00:30:11.677+00:00"},"s":"I",  "c":"REPL",     "id":6015317, "ctx":"initandlisten","msg":"Setting new configuration state","attr":{"newState":"ConfigReplicationDisabled","oldState":"ConfigPreStart"}}
music-bot-2-mongo-1  | {"t":{"$date":"2022-09-10T00:30:11.677+00:00"},"s":"I",  "c":"STORAGE",  "id":22262,   "ctx":"initandlisten","msg":"Timestamp monitor starting"}
music-bot-2-mongo-1  | {"t":{"$date":"2022-09-10T00:30:11.678+00:00"},"s":"I",  "c":"NETWORK",  "id":23015,   "ctx":"listener","msg":"Listening on","attr":{"address":"/tmp/mongodb-27017.sock"}}
music-bot-2-mongo-1  | {"t":{"$date":"2022-09-10T00:30:11.678+00:00"},"s":"I",  "c":"NETWORK",  "id":23015,   "ctx":"listener","msg":"Listening on","attr":{"address":"0.0.0.0"}}
music-bot-2-mongo-1  | {"t":{"$date":"2022-09-10T00:30:11.678+00:00"},"s":"I",  "c":"NETWORK",  "id":23016,   "ctx":"listener","msg":"Waiting for connections","attr":{"port":27017,"ssl":"off"}}
music-bot-2-mongo-1  | {"t":{"$date":"2022-09-10T00:30:12.788+00:00"},"s":"I",  "c":"NETWORK",  "id":22943,   "ctx":"listener","msg":"Connection accepted","attr":{"remote":"172.22.0.3:46678","uuid":"04e2901a-f80a-4f53-8c58-65732906073d","connectionId":1,"connectionCount":1}}
music-bot-2-mongo-1  | {"t":{"$date":"2022-09-10T00:30:12.788+00:00"},"s":"I",  "c":"NETWORK",  "id":22943,   "ctx":"listener","msg":"Connection accepted","attr":{"remote":"172.22.0.3:46676","uuid":"3338b9a5-eb82-49a3-9e0d-5f6a0545e29e","connectionId":2,"connectionCount":2}}
music-bot-2-mongo-1  | {"t":{"$date":"2022-09-10T00:30:12.793+00:00"},"s":"I",  "c":"NETWORK",  "id":51800,   "ctx":"conn2","msg":"client metadata","attr":{"remote":"172.22.0.3:46676","client":"conn2","doc":{"driver":{"name":"mongo-java-driver|reactive-streams","version":"4.7.1"},"os":{"type":"Linux","name":"Linux","architecture":"amd64","version":"5.10.16.3-microsoft-standard-WSL2"},"platform":"Java/IBM Corporation/18.0.2+9"}}}
music-bot-2-mongo-1  | {"t":{"$date":"2022-09-10T00:30:12.793+00:00"},"s":"I",  "c":"NETWORK",  "id":51800,   "ctx":"conn1","msg":"client metadata","attr":{"remote":"172.22.0.3:46678","client":"conn1","doc":{"driver":{"name":"mongo-java-driver|reactive-streams","version":"4.7.1"},"os":{"type":"Linux","name":"Linux","architecture":"amd64","version":"5.10.16.3-microsoft-standard-WSL2"},"platform":"Java/IBM Corporation/18.0.2+9"}}}
music-bot-2-bot-1    | 2022-09-10 00:30:12.787 [main] INFO  org.mongodb.driver.client - MongoClient with metadata {"driver": {"name": "mongo-java-driver|reactive-streams", "version": "4.7.1"}, "os": {"type": "Linux", "name": "Linux", "architecture": "amd64", "version": "5.10.16.3-microsoft-standard-WSL2"}, "platform": "Java/IBM Corporation/18.0.2+9"} created with settings MongoClientSettings{readPreference=primary, writeConcern=WriteConcern{w=null, wTimeout=null ms, journal=null}, retryWrites=true, retryReads=true, readConcern=ReadConcern{level=null}, credential=MongoCredential{mechanism=null, userName='bot', source='admin', password=<hidden>, mechanismProperties=<hidden>}, streamFactoryFactory=null, commandListeners=[], codecRegistry=ProvidersCodecRegistry{codecProviders=[ProvidersCodecRegistry{codecProviders=[ValueCodecProvider{}, BsonValueCodecProvider{}, DBRefCodecProvider{}, DBObjectCodecProvider{}, DocumentCodecProvider{}, IterableCodecProvider{}, MapCodecProvider{}, GeoJsonCodecProvider{}, GridFSFileCodecProvider{}, Jsr310CodecProvider{}, JsonObjectCodecProvider{}, BsonCodecProvider{}, EnumCodecProvider{}, com.mongodb.Jep395RecordCodecProvider@62b32d6c]}, org.litote.kmongo.service.CustomCodecProvider@c6960ffb, org.litote.kmongo.serialization.SerializationClassMappingTypeService$coreCodecRegistry$1@5a6a862c]}, clusterSettings={hosts=[mongo:27017], srvServiceName=mongodb, mode=SINGLE, requiredClusterType=UNKNOWN, requiredReplicaSetName='null', serverSelector='null', clusterListeners='[]', serverSelectionTimeout='30000 ms', localThreshold='30000 ms'}, socketSettings=SocketSettings{connectTimeoutMS=10000, readTimeoutMS=0, receiveBufferSize=0, sendBufferSize=0}, heartbeatSocketSettings=SocketSettings{connectTimeoutMS=10000, readTimeoutMS=10000, receiveBufferSize=0, sendBufferSize=0}, connectionPoolSettings=ConnectionPoolSettings{maxSize=100, minSize=0, maxWaitTimeMS=120000, maxConnectionLifeTimeMS=0, maxConnectionIdleTimeMS=0, maintenanceInitialDelayMS=0, maintenanceFrequencyMS=60000, connectionPoolListeners=[], maxConnecting=2}, serverSettings=ServerSettings{heartbeatFrequencyMS=10000, minHeartbeatFrequencyMS=500, serverListeners='[]', serverMonitorListeners='[]'}, sslSettings=SslSettings{enabled=false, invalidHostNameAllowed=false, context=null}, applicationName='null', compressorList=[], uuidRepresentation=UNSPECIFIED, serverApi=null, autoEncryptionSettings=null, contextProvider=null}
music-bot-2-bot-1    | 2022-09-10 00:30:12.806 [cluster-ClusterId{value='631bda94ba7f74728e753c78', description='null'}-mongo:27017] INFO  org.mongodb.driver.connection - Opened connection [connectionId{localValue:1, serverValue:2}] to mongo:27017
music-bot-2-bot-1    | 2022-09-10 00:30:12.806 [cluster-rtt-ClusterId{value='631bda94ba7f74728e753c78', description='null'}-mongo:27017] INFO  org.mongodb.driver.connection - Opened connection [connectionId{localValue:2, serverValue:1}] to mongo:27017
music-bot-2-bot-1    | 2022-09-10 00:30:12.806 [cluster-ClusterId{value='631bda94ba7f74728e753c78', description='null'}-mongo:27017] INFO  org.mongodb.driver.cluster - Monitor thread successfully connected to server with description ServerDescription{address=mongo:27017, type=STANDALONE, state=CONNECTED, ok=true, minWireVersion=0, maxWireVersion=17, maxDocumentSize=16777216, logicalSessionTimeoutMinutes=30, roundTripTimeNanos=14144669}
music-bot-2-bot-1    | 2022-09-10 00:30:12.822 [main] INFO  o.pf4j.DefaultPluginStatusProvider - Enabled plugins: []
music-bot-2-bot-1    | 2022-09-10 00:30:12.823 [main] INFO  o.pf4j.DefaultPluginStatusProvider - Disabled plugins: []
music-bot-2-bot-1    | 2022-09-10 00:30:12.825 [main] INFO  org.pf4j.DefaultPluginManager - PF4J version 3.7.0 in 'deployment' mode
music-bot-2-bot-1    | 2022-09-10 00:30:12.856 [main] DEBUG org.pf4j.AbstractPluginManager - Lookup plugins in '[/usr/app/plugins]'
music-bot-2-bot-1    | 2022-09-10 00:30:12.861 [main] INFO  org.pf4j.AbstractPluginManager - No plugins
music-bot-2-bot-1    | 2022-09-10 00:30:12.861 [main] DEBUG d.s.m.core.plugin.PluginUpdater - No updates found
music-bot-2-bot-1    | 2022-09-10 00:30:12.861 [main] DEBUG o.p.update.DefaultUpdateRepository - Read plugins of 'c4ea153ee891e283' repository from 'https://storage.googleapis.com/mikbot-plugins/plugins.json'
music-bot-2-bot-1    | 2022-09-10 00:30:13.678 [main] DEBUG o.p.update.DefaultUpdateRepository - Found 25 plugins in repository 'c4ea153ee891e283'
music-bot-2-bot-1    | 2022-09-10 00:30:13.681 [main] DEBUG d.s.m.core.plugin.PluginLoader - Built translation provider graph: {}
music-bot-2-bot-1    | 2022-09-10 00:30:13.703 [main] DEBUG org.pf4j.AbstractExtensionFinder - Finding extensions of extension point 'dev.schlaubi.musicbot.core.sentry.SentryExtensionPoint'
music-bot-2-bot-1    | 2022-09-10 00:30:13.703 [main] DEBUG org.pf4j.LegacyExtensionFinder - Reading extensions storages from classpath
music-bot-2-bot-1    | 2022-09-10 00:30:13.703 [main] DEBUG org.pf4j.LegacyExtensionFinder - Read 'file:/usr/app/lib/pf4j-update-2.3.0.jar!/META-INF/extensions.idx'
music-bot-2-bot-1    | 2022-09-10 00:30:13.704 [main] DEBUG org.pf4j.AbstractExtensionFinder - No extensions found
music-bot-2-bot-1    | 2022-09-10 00:30:13.704 [main] DEBUG org.pf4j.LegacyExtensionFinder - Reading extensions storages from plugins
music-bot-2-bot-1    | 2022-09-10 00:30:13.704 [main] DEBUG d.s.m.c.p.DependencyCheckingExtensionFinder - Finding extensions of extension point 'dev.schlaubi.musicbot.core.sentry.SentryExtensionPoint' for plugin 'null'
music-bot-2-bot-1    | 2022-09-10 00:30:13.705 [main] DEBUG org.pf4j.AbstractExtensionFinder - No extensions found for extension point 'dev.schlaubi.musicbot.core.sentry.SentryExtensionPoint'
music-bot-2-bot-1    | Exception in thread "main" dev.kord.core.exception.KordInitializationException: Something went wrong while initializing Kord, make sure the bot token you entered is valid.{"message": "401: Unauthorized", "code": 0}
music-bot-2-bot-1    |
music-bot-2-bot-1    |  at dev.kord.core.builder.kord.KordBuilder.getGatewayInfo(KordBuilder.kt:223)
music-bot-2-bot-1    |  at dev.kord.core.builder.kord.KordBuilder.access$getGatewayInfo(KordBuilder.kt:61)
music-bot-2-bot-1    |  at dev.kord.core.builder.kord.KordBuilder$getGatewayInfo$1.invokeSuspend(KordBuilder.kt)
music-bot-2-bot-1    |  at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
music-bot-2-bot-1    |  at io.ktor.util.pipeline.SuspendFunctionGun.resumeRootWith(SuspendFunctionGun.kt:138)
music-bot-2-bot-1    |  at io.ktor.util.pipeline.SuspendFunctionGun.loop(SuspendFunctionGun.kt:112)
music-bot-2-bot-1    |  at io.ktor.util.pipeline.SuspendFunctionGun.access$loop(SuspendFunctionGun.kt:14)
music-bot-2-bot-1    |  at io.ktor.util.pipeline.SuspendFunctionGun$continuation$1.resumeWith(SuspendFunctionGun.kt:62)
music-bot-2-bot-1    |  at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
music-bot-2-bot-1    |  at io.ktor.util.pipeline.SuspendFunctionGun.resumeRootWith(SuspendFunctionGun.kt:138)
music-bot-2-bot-1    |  at io.ktor.util.pipeline.SuspendFunctionGun.loop(SuspendFunctionGun.kt:112)
music-bot-2-bot-1    |  at io.ktor.util.pipeline.SuspendFunctionGun.access$loop(SuspendFunctionGun.kt:14)
music-bot-2-bot-1    |  at io.ktor.util.pipeline.SuspendFunctionGun$continuation$1.resumeWith(SuspendFunctionGun.kt:62)
music-bot-2-bot-1    |  at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
music-bot-2-bot-1    |  at io.ktor.util.pipeline.SuspendFunctionGun.resumeRootWith(SuspendFunctionGun.kt:138)
music-bot-2-bot-1    |  at io.ktor.util.pipeline.SuspendFunctionGun.loop(SuspendFunctionGun.kt:112)
music-bot-2-bot-1    |  at io.ktor.util.pipeline.SuspendFunctionGun.access$loop(SuspendFunctionGun.kt:14)
music-bot-2-bot-1    |  at io.ktor.util.pipeline.SuspendFunctionGun$continuation$1.resumeWith(SuspendFunctionGun.kt:62)
music-bot-2-bot-1    |  at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
music-bot-2-bot-1    |  at io.ktor.util.pipeline.SuspendFunctionGun.resumeRootWith(SuspendFunctionGun.kt:138)
music-bot-2-mongo-1  | {"t":{"$date":"2022-09-10T00:30:14.318+00:00"},"s":"I",  "c":"-",        "id":20883,   "ctx":"conn2","msg":"Interrupted operation as its client disconnected","attr":{"opId":28}}
music-bot-2-bot-1    |  at io.ktor.util.pipeline.SuspendFunctionGun.loop(SuspendFunctionGun.kt:112)
music-bot-2-mongo-1  | {"t":{"$date":"2022-09-10T00:30:14.319+00:00"},"s":"I",  "c":"NETWORK",  "id":22944,   "ctx":"conn1","msg":"Connection ended","attr":{"remote":"172.22.0.3:46678","uuid":"04e2901a-f80a-4f53-8c58-65732906073d","connectionId":1,"connectionCount":1}}
music-bot-2-bot-1    |  at io.ktor.util.pipeline.SuspendFunctionGun.access$loop(SuspendFunctionGun.kt:14)
music-bot-2-mongo-1  | {"t":{"$date":"2022-09-10T00:30:14.319+00:00"},"s":"I",  "c":"NETWORK",  "id":22944,   "ctx":"conn2","msg":"Connection ended","attr":{"remote":"172.22.0.3:46676","uuid":"3338b9a5-eb82-49a3-9e0d-5f6a0545e29e","connectionId":2,"connectionCount":0}}
music-bot-2-bot-1    |  at io.ktor.util.pipeline.SuspendFunctionGun$continuation$1.resumeWith(SuspendFunctionGun.kt:62)
music-bot-2-bot-1    |  at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
music-bot-2-bot-1    |  at io.ktor.util.pipeline.SuspendFunctionGun.resumeRootWith(SuspendFunctionGun.kt:138)
music-bot-2-bot-1    |  at io.ktor.util.pipeline.SuspendFunctionGun.loop(SuspendFunctionGun.kt:112)
music-bot-2-bot-1    |  at io.ktor.util.pipeline.SuspendFunctionGun.access$loop(SuspendFunctionGun.kt:14)
music-bot-2-bot-1    |  at io.ktor.util.pipeline.SuspendFunctionGun$continuation$1.resumeWith(SuspendFunctionGun.kt:62)
music-bot-2-bot-1    |  at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
music-bot-2-bot-1    |  at kotlinx.coroutines.DispatchedTaskKt.resume(DispatchedTask.kt:178)
music-bot-2-bot-1    |  at kotlinx.coroutines.DispatchedTaskKt.dispatch(DispatchedTask.kt:166)
music-bot-2-bot-1    |  at kotlinx.coroutines.CancellableContinuationImpl.dispatchResume(CancellableContinuationImpl.kt:397)
music-bot-2-bot-1    |  at kotlinx.coroutines.CancellableContinuationImpl.resumeImpl(CancellableContinuationImpl.kt:431)music-bot-2-bot-1    |  at kotlinx.coroutines.CancellableContinuationImpl.resumeImpl$default(CancellableContinuationImpl.kt:420)
music-bot-2-bot-1    |  at kotlinx.coroutines.CancellableContinuationImpl.resumeWith(CancellableContinuationImpl.kt:328)music-bot-2-bot-1    |  at kotlinx.coroutines.ResumeAwaitOnCompletion.invoke(JobSupport.kt:1413)
music-bot-2-bot-1    |  at kotlinx.coroutines.JobSupport.notifyCompletion(JobSupport.kt:1520)
music-bot-2-bot-1    |  at kotlinx.coroutines.JobSupport.completeStateFinalization(JobSupport.kt:323)
music-bot-2-bot-1    |  at kotlinx.coroutines.JobSupport.finalizeFinishingState(JobSupport.kt:240)
music-bot-2-bot-1    |  at kotlinx.coroutines.JobSupport.tryMakeCompletingSlowPath(JobSupport.kt:906)
music-bot-2-bot-1    |  at kotlinx.coroutines.JobSupport.tryMakeCompleting(JobSupport.kt:863)
music-bot-2-bot-1    |  at kotlinx.coroutines.JobSupport.makeCompletingOnce$kotlinx_coroutines_core(JobSupport.kt:828)
music-bot-2-bot-1    |  at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.kt:100)
music-bot-2-bot-1    |  at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
music-bot-2-bot-1    |  at kotlinx.coroutines.UndispatchedCoroutine.afterResume(CoroutineContext.kt:233)
music-bot-2-bot-1    |  at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.kt:102)
music-bot-2-bot-1    |  at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
music-bot-2-bot-1    |  at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
music-bot-2-bot-1    |  at kotlinx.coroutines.internal.LimitedDispatcher.run(LimitedDispatcher.kt:42)
music-bot-2-bot-1    |  at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:95)
music-bot-2-bot-1    |  at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
music-bot-2-bot-1    |  at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
music-bot-2-bot-1    |  at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
music-bot-2-bot-1    |  at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)
music-bot-2-bot-1 exited with code 1

**Comment by DRSchlaubi** [comment]
> Something went wrong while initializing Kord, **make sure the bot token you entered is valid.**{"message": "401: Unauthorized", "code": 0}

**Comment by QuantumRage100** [comment]
I'm 90% sure I have a valid bot token, I was planning on replacing my current self hosted music bot with this one, and I used the same token, after you mentioned something might be wrong with the token I generated a new one for the bot and it still gave me the same error, am I putting the token in incorrectly by any chance? I will take a screen shot as an example (not with my active token of course)
![image](https://user-images.githubusercontent.com/111104378/189481355-9e0d271a-a21a-4525-9ee0-0dd0ba80a160.png)

**Comment by NyCodeGHG** [comment]
you did not remove the <> characters from the token

**Comment by QuantumRage100** [comment]
you know it's funny, because I tried removing the < > around everything but that didn't work previously, I'm just realizing now that when I create a docker image it uses the .env file but after that it will ignore changes, so every time I make an edit in the .env file I need to remake or update the docket image, anyway thanks it seems to be pulling the bot token now

I am having a different issue now which may be related to my JDK version, I saw in one of the older documents you were recommending jdk 13 but that one seems a little outdated (it isn't even listed on the jdk main download page anymore)
which JDK version do you recommend? I'm currently running 17

and here is the error I am seeing in the console

music-bot-bot-1    | 2022-09-11 02:10:40.472 [DefaultDispatcher-worker-18] ERROR [Koin] - Instance creation error : could not create instance for [Singleton:'com.kotlindiscord.kord.extensions.sentry.SentryAdapter',binds:com.kotlindiscord.kord.extensions.sentry.SentryAdapter]: java.lang.IllegalArgumentException: DSN is required. Use empty string to disable SDK.

I will attach the entire console log output as a text document as well if this information is not enough
[koin - instance creation error.txt](https://github.com/DRSchlaubi/mikbot/files/9541653/koin.-.instance.creation.error.txt)

**Comment by NyCodeGHG** [comment]
When you're using docker you don't need a jdk. The JDK we're using is included in the docker image. I'm not sure about the sentry thing. Maybe @DRSchlaubi knows how to fix this

**Comment by DRSchlaubi** [comment]
Set `ENVIRONMENT=DEVELOPMENT` to disable sentry

**Comment by QuantumRage100** [comment]
awesome yep that seemed to work, alright I'm starting to wrap my head around how complex this bot is, I must say this would not be an easy bot to set up for most users but, wow it seems powerful, so I have the main uh "framework" I guess you would call it running just fine, bot shows up in the server as running etc, but I don't have any commands yet, I want to set this up as a music bot, I have the image_color_service running and listening on http://0.0.0.0:8080, I think this is working properly
I installed happi.dev using npm I happi-dev-sdk (to the same folder as the music bot, I'm not sure if I should put it anywhere else and I tried to run it with npm run but, I am not 100% sure if this is a service in need to run, or if the bot will just call for it when it needs, I'm hoping just having it here in the correct location is enough but I'm not 100% sure

the bottom of my .env now looks like this
![image](https://user-images.githubusercontent.com/111104378/189537025-bc2d1882-6a74-4502-a655-320886548ff3.png)

when I run this command I get this response
C:\Music-Bot>docker-compose exec mongo mongo -u bot -p bot
OCI runtime exec failed: exec failed: unable to start container process: exec: "mongo": executable file not found in $PATH: unknown
still the plugins appear to be loading correctly, I hope >~<

when I run the bot I am getting this error message I will add the entire console log as a text file again incase it is important

bot_1    | 2022-09-11 15:18:00.812 [DefaultDispatcher-worker-1] ERROR dev.kord.gateway.DefaultGateway - Gateway closed: 4014 Disallowed intent(s).
[4014 Disallowed intent(s).txt](https://github.com/DRSchlaubi/mikbot/files/9542994/4014.Disallowed.intent.s.txt)

also thankyou very much for the help you have given me, I wouldn't be able to figure out every little step of this on my own, I like to think I'm fairly with it when it comes to technology but some of this stuff is very new to me

**Comment by DRSchlaubi** [comment]
The music plugin requires the Guild Messages intent to be enabled in the Discord Developer Dashboard

**Comment by DRSchlaubi** [comment]
also try docker-compose exec mongo mongo sh-u bot -p bot****

**Comment by QuantumRage100** [comment]
yep the guild members intent seemed to fixed the crashing issue again ty :)

that command seems to be working better, it is telling me authentication failed now when I run it

C:\Music-Bot>docker-compose exec mongo mongosh -u bot -p bot****
Current Mongosh Log ID: 631e8e345b3f4416ad3c3123
Connecting to:          mongodb://<credentials>@127.0.0.1:27017/?directConnection=true&serverSelectionTimeoutMS=2000&appName=mongosh+1.5.4
MongoServerError: Authentication failed.

I can now /play in the server, and the bot will give me options to play something I get told that the application did not respond

[the application did not respond.txt](https://github.com/DRSchlaubi/mikbot/files/9544052/the.application.did.not.respond.txt)
