### ISSUE TITLE
Error during download of plugin votebot

### ISSUE THREAD

**Issue by dmitrylavrenov** [DRSchlaubi/mikbot#277]
We would like to run self-hosted mikbot (ghcr.io/drschlaubi/mikmusic/bot) with votebot plugin. Tried to deploy it based on https://github.com/StckOverflw/mikbot/blob/main/votebot/README.md with
```
- name: DOWNLOAD_PLUGINS
   value: votebot
- name: PIE_CHART_SERVICE_URL
   value: https://pie-chart-service.nc-01.votebot.space/
```

But we get the following error:
```
2023-06-26 14:24:11.744 [main] DEBUG o.p.update.DefaultUpdateRepository - Read plugins of 'c8757b615cfdffca' repository from 'https://storage.googleapis.com/mikbot-plugins/plugins.json'
2023-06-26 14:24:37.243 [main] DEBUG o.p.update.DefaultUpdateRepository - Found 25 plugins in repository 'c8757b615cfdffca'
2023-06-26 14:24:37.344 [main] INFO  d.s.m.core.plugin.PluginUpdater - Attempting to download the following plugins: [PluginSpec(id=votebot, version=null)]
Exception in thread "main" org.pf4j.PluginRuntimeException: Error during download of plugin votebot
        at org.pf4j.update.UpdateManager.downloadPlugin(UpdateManager.java:273)
        at org.pf4j.update.UpdateManager.installPlugin(UpdateManager.java:241)
        at dev.schlaubi.musicbot.core.plugin.PluginUpdater.downloadRequestedPlugins(PluginUpdater.kt:120)
        at dev.schlaubi.musicbot.core.plugin.PluginUpdater.checkForUpdates$mikmusic(PluginUpdater.kt:30)
        at dev.schlaubi.musicbot.core.plugin.PluginLoader.loadPlugins(PluginLoader.kt:58)
        at dev.schlaubi.musicbot.LauncherKt.loadPlugins(Launcher.kt:29)
        at dev.schlaubi.musicbot.LauncherKt.main(Launcher.kt:15)
        at dev.schlaubi.musicbot.LauncherKt$main$2.invoke(Launcher.kt)
        at dev.schlaubi.musicbot.LauncherKt$main$2.invoke(Launcher.kt)
        at kotlin.coroutines.intrinsics.IntrinsicsKt__IntrinsicsJvmKt$createCoroutineUnintercepted$$inlined$createCoroutineFromSuspendFunction$IntrinsicsKt__IntrinsicsJvmKt$1.invokeSuspend(IntrinsicsJvm.kt:205)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlin.coroutines.ContinuationKt.startCoroutine(Continuation.kt:115)
        at kotlin.coroutines.jvm.internal.RunSuspendKt.runSuspend(RunSuspend.kt:19)
        at dev.schlaubi.musicbot.LauncherKt.main(Launcher.kt)
Caused by: io.ktor.client.plugins.HttpRequestTimeoutException: Request timeout has expired [url=https://storage.googleapis.com/mikbot-plugins/votebot/3.24.0/plugin-votebot-3.24.0.zip, request_timeout=unknown ms]
        at io.ktor.client.engine.cio.EndpointKt$setupTimeout$timeoutJob$1.invokeSuspend(Endpoint.kt:252)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)
```

Would like to note that `game-animator` plugin works in the happy path. 

CC: @MOZGIII

**Comment by dmitrylavrenov** [comment]
> Use this Docker image: https://github.com/Votebot/votebot-plugin/pkgs/container/votebot-plugin

Thanks, will check!

**Comment by dmitrylavrenov** [comment]
> Don't pull the tags ending with .sig

Tried, then I have unknown manifest
```
docker pull ghcr.io/votebot/votebot-plugin:sha256-8c5c636c0b8beaea613e0cde81b6477ace2f2591ae8e7096c2041e8a2f16b3ca
Error response from daemon: manifest unknown
```

**Comment by dmitrylavrenov** [comment]
Even tried 

```
docker pull ghcr.io/votebot/votebot-plugin                        
Using default tag: latest
Error response from daemon: manifest unknown
```

**Comment by DRSchlaubi** [comment]
Use this one

**Comment by dmitrylavrenov** [comment]
> Use this one

Which one?

**Comment by DRSchlaubi** [comment]
https://github.com/Votebot/votebot-plugin/pkgs/container/votebot-plugin/104402746?tag=main
