### ISSUE TITLE
Sponsorblock exception

### ISSUE THREAD

**Issue by DRSchlaubi** [DRSchlaubi/mikbot#70]
```
2022-01-07T21:12:51.563397345Z Exception in thread "DefaultDispatcher-worker-12" java.lang.NullPointerException: Cannot invoke "java.lang.Object.hashCode()" because "<parameter1>" is null
2022-01-07T21:12:51.563699070Z at java.base/java.util.concurrent.ConcurrentHashMap.replaceNode(Unknown Source)
2022-01-07T21:12:51.563788930Z at java.base/java.util.concurrent.ConcurrentHashMap.remove(Unknown Source)
2022-01-07T21:12:51.563863192Z at dev.schlaubi.mikmusic.sponsorblock.SponsorBlockKt.deleteSponsorBlockCache(SponsorBlock.kt:53)
2022-01-07T21:12:51.564095364Z at dev.schlaubi.mikmusic.player.MusicPlayer.onTrackEnd(MusicPlayer.kt:232)
2022-01-07T21:12:51.564331975Z at dev.schlaubi.mikmusic.player.MusicPlayer.access$onTrackEnd(MusicPlayer.kt:34)
2022-01-07T21:12:51.564556161Z at dev.schlaubi.mikmusic.player.MusicPlayer$2.invoke(MusicPlayer.kt:59)
2022-01-07T21:12:51.564786440Z at dev.schlaubi.mikmusic.player.MusicPlayer$2.invoke(MusicPlayer.kt:59)
2022-01-07T21:12:51.564963307Z at dev.schlaubi.mikmusic.player.MusicPlayer$special$$inlined$on$default$2$1.invokeSuspend(EventSource.kt:43)
2022-01-07T21:12:51.565288025Z at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
2022-01-07T21:12:51.565613665Z at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
2022-01-07T21:12:51.565696052Z at kotlinx.coroutines.internal.LimitedDispatcher.run(LimitedDispatcher.kt:39)
2022-01-07T21:12:51.565701803Z at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:95)
2022-01-07T21:12:51.565704217Z at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
2022-01-07T21:12:51.565706553Z at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
2022-01-07T21:12:51.565708937Z at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
2022-01-07T21:12:51.565711081Z at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)
```

**Comment by NyCodeGHG** [comment]
> `<parameter1>`
that sounds funny
